WebProgramlamaDeneme_25/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebProgramlamaDeneme_25.Models;

namespace WebProgramlamaDeneme_25.Controllers
{
    public class HomeController : Controller
    {
        private ProjeDBEntities db = new ProjeDBEntities();


        // GET: Makales
        public ActionResult Anasayfa()
        {
            var makale = db.Makale.Include(m => m.Uye);
            return View(makale.OrderByDescending(i => i.Tarih).Take(5).ToList());
        }


        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

WebProgramlamaDeneme_25/Controllers/MakalesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebProgramlamaDeneme_25.Models;

namespace WebProgramlamaDeneme_25.Controllers
{
    public class MakalesController : Controller
    {
        private ProjeDBEntities db = new ProjeDBEntities();

        // GET: Makales
        public ActionResult Ekranayaz()
        {
            var makale = db.Makale.Include(m => m.Uye);
            return View(makale.ToList());
        }

        // GET: Makales/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Makale makale = db.Makale.Find(id);
            if (makale == null)
            {
                return HttpNotFound();
            }
            return View(makale);
        }

        // GET: Makales/Create
        public ActionResult Create()
        {
            ViewBag.UyeId = new SelectList(db.Uye, "UyeId", "KullaniciAdi");
            return View();
        }

        // POST: Makales/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MakaleId,UyeId,Baslik,İcerik,Tarih,Saat")] Makale makale)
        {
            if (ModelState.IsValid)
            {
                db.Makale.Add(makale);
                db.SaveChanges();
                return RedirectToAction("Ekranayaz");
            }

            ViewBag.UyeId = new SelectList(db.Uye, "UyeId", "KullaniciAdi", makale.UyeId);
            return View(makale);
        }

        // GET: Makales/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Makale makale = db.Makale.Find(id);
            if (makale == null)
            {
                return HttpNotFound();
            }
            ViewBag.UyeId = new SelectList(db.Uye, "UyeId", "KullaniciAdi", makale.UyeId);
            return View(makale);
        }

        // POST: Makales/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MakaleId,UyeId,Baslik,İcerik,Tarih,Saat")] Makale makale)
        {
            if (ModelState.IsValid)
            {
                db.Entry(makale).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Ekranayaz");
            }
            ViewBag.UyeId = new SelectList(db.Uye, "UyeId", "KullaniciAdi", makale.UyeId);
            return View(makale);
        }

        // GET: Makales/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Makale makale = db.Makale.Find(id);
            if (makale == null)
            {
                return HttpNotFound();
            }
            return View(makale);
        }

        // POST: Makales/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Makale makale = db.Makale.Find(id);
            db.Makale.Remove(makale);
            db.SaveChanges();
            return RedirectToAction("Ekranayaz");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebProgramlamaDeneme_25/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

WebProgramlamaDeneme_25/Views/Home/Anasayfa.cshtml
@model IEnumerable<WebProgramlamaDeneme_25.Models.Makale>

@{
    ViewBag.Title = "Anasayfa";
    Layout = "~/Views/Shared/_Layout.cshtml";
}




<section id="contentbody">
    <div class="container">
        <div class="row">
            <div class="col-md-2">
                <div class="row">
                    <div class="middlebar_content">
                        <div class="popular_categori  wow fadeInUp">
                            <h2 class="limeblue_bg">@Resources.Anasayfa.last</h2>


                            <ul class="poplr_catgnva">
                                @foreach (var item in Model)
                                {
                                    <li><a href="" #>@Html.DisplayFor(modelItem => item.Baslik)</a></li>
                                }
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-10">
                <div class="row">
                    <div class="rightbar_content">
                        <div class="col-md-9 single_blog_sidebar wow fadeInUp">
                            <table>
                                <thead>
                                    <tr>
                                        <th scope="col">@Html.ActionLink(@Resources.Anasayfa.Math, "Ekranayaz", "Makales")</th>
                                        <th scope="col" align="center"><img src="@Url.Content("~/Content/Temaicerik/")images/yorum.ico" alt="Yorum"></th>
                                        <th scope="col" align="center"><img src="@Url.Content("~/Content/Temaicerik/")images/saat.ico" alt="Saat"></th>
                                        <th scope="col" align="center"><img src="@Url.Content("~/Content/Temaicerik/")images/tarih.ico" alt="Tarih"></th>
                                    </tr>
                                </thead>
                                @foreach (var item in Model)
                                {

                                    <tbody>
                                        <tr>
                                            <td>
                                                <strong class="book-title">@Html.DisplayFor(modelItem => item.Baslik)</strong>
                                                <span class="text-offset">@Html.DisplayFor(modelItem => item.Uye.KullaniciAdi)</span>
                                            </td>
                                            <td class="item-qty">atılan yorum sayısı<img src="@Url.Content("~/Content/Temaicerik/")images/yorum.ico" alt="Yorum"></td>
                                            <td class="item-price">@Html.DisplayFor(modelItem => item.Tarih)</td>
                                            <td class="item-price">@Html.DisplayFor(modelItem => item.Saat)</td>
                                        </tr>
                                    </tbody>

                                }

                            </table>
                        </div>
                        <div class="col-md-9 single_blog_sidebar wow fadeInUp">
                            <table>
                                <thead>
                                    <tr>
                                        <th scope="col">@Html.ActionLink(@Resources.Anasayfa.geo, "Ekranayaz", "Makales")</th>
                                        <th scope="col" align="center"><img src="@Url.Content("~/Content/Temaicerik/")images/yorum.ico" alt="Yorum"></th>
                                        <th scope="col" align="center"><img src="@Url.Content("~/Content/Temaicerik/")images/saat.ico" alt="Saat"></th>
                                        <th scope="col" align="center"><img src="@Url.Content("~/Content/Temaicerik/")images/tarih.ico" alt="Tarih"></th>
                                    </tr>
                                </thead>
                                @foreach (var item in Model)
                                {

                                    <tbody>
                                        <tr>
                                            <td>
                                                <strong class="book-title">@Html.DisplayFor(modelItem => item.Baslik)</strong>
                                                <span class="text-offset">@Html.DisplayFor(modelItem => item.Uye.KullaniciAdi)</span>
                                            </td>
                                            <td class="item-qty">atılan yorum sayısı<img src="@Url.Content("~/Content/Temaicerik/")images/yorum.ico" alt="Yorum"></td>
                                            <td class="item-price">@Html.DisplayFor(modelItem => item.Tarih)</td>
                                            <td class="item-price">@Html.DisplayFor(modelItem => item.Saat)</td>
                                        </tr>
                                    </tbody>

                                }
                            </table>
                        </div>
                        <div class="col-md-9 single_blog_sidebar wow fadeInUp">
                            <table>
                                <thead>
                                    <tr>
                                        <th scope="col">@Html.ActionLink(@Resources.Anasayfa.physic, "Ekranayaz", "Makales")</th>
                                        <th scope="col" align="center"><img src="@Url.Content("~/Content/Temaicerik/")images/yorum.ico" alt="Yorum"></th>
                                        <th scope="col" align="center"><img src="@Url.Content("~/Content/Temaicerik/")images/saat.ico" alt="Saat"></th>
                                        <th scope="col" align="center"><img src="@Url.Content("~/Content/Temaicerik/")images/tarih.ico" alt="Tarih"></th>
                                    </tr>
                                </thead>
                                @foreach (var item in Model)
                                {

                                    <tbody>
                                        <tr>
                                            <td>
                                                <strong class="book-title">@Html.DisplayFor(modelItem => item.Baslik)</strong>
                                                <span class="text-offset">@Html.DisplayFor(modelItem => item.Uye.KullaniciAdi)</span>
                                            </td>
                                            <td class="item-qty">atılan yorum sayısı<img src="@Url.Content("~/Content/Temaicerik/")images/yorum.ico" alt="Yorum"></td>
                                            <td class="item-price">@Html.DisplayFor(modelItem => item.Tarih)</td>
                                            <td class="item-price">@Html.DisplayFor(modelItem => item.Saat)</td>
                                        </tr>
                                    </tbody>

                                }
                            </table>
                        </div>
                        <div class="col-md-9 single_blog_sidebar wow fadeInUp">
                            <table>
                                <thead>
                                    <tr>
                                        <th scope="col">@Html.ActionLink(@Resources.Anasayfa.chemistry, "Ekranayaz", "Makales")</th>
                                        <th scope="col" align="center"><img src="@Url.Content("~/Content/Temaicerik/")images/yorum.ico" alt="Yorum"></th>
                                        <th scope="col" align="center"><img src="@Url.Content("~/Content/Temaicerik/")images/saat.ico" alt="Saat"></th>
                                        <th scope="col" align="center"><img src="@Url.Content("~/Content/Temaicerik/")images/tarih.ico" alt="Tarih"></th>
                                    </tr>
                                </thead>
                                @foreach (var item in Model)
                                {

                                    <tbody>
                                        <tr>
                                            <td>
                                                <strong class="book-title">@Html.DisplayFor(modelItem => item.Baslik)</strong>
                                                <span class="text-offset">@Html.DisplayFor(modelItem => item.Uye.KullaniciAdi)</span>
                                            </td>
                                            <td class="item-qty">atılan yorum sayısı<img src="@Url.Content("~/Content/Temaicerik/")images/yorum.ico" alt="Yorum"></td>
                                            <td class="item-price">@Html.DisplayFor(modelItem => item.Tarih)</td>
                                            <td class="item-price">@Html.DisplayFor(modelItem => item.Saat)</td>
                                        </tr>
                                    </tbody>

                                }
                            </table>
                        </div>
                        <div class="col-md-9 single_blog_sidebar wow fadeInUp">
                            <table>
                                <thead>
                                    <tr>
                                        <th scope="col">@Html.ActionLink(@Resources.Anasayfa.bio, "Ekranayaz", "Makales")</th>
                                        <th scope="col" align="center"><img src="@Url.Content("~/Content/Temaicerik/")images/yorum.ico" alt="Yorum"></th>
                                        <th scope="col" align="center"><img src="@Url.Content("~/Content/Temaicerik/")images/saat.ico" alt="Saat"></th>
                                        <th scope="col" align="center"><img src="@Url.Content("~/Content/Temaicerik/")images/tarih.ico" alt="Tarih"></th>
                                    </tr>
                                </thead>
                                @foreach (var item in Model)
                                {
                                    <tbody>
                                        <tr>
                                            <td>
                                                <strong class="book-title">@Html.DisplayFor(modelItem => item.Baslik)</strong>
                                                <span class="text-offset">@Html.DisplayFor(modelItem => item.Uye.KullaniciAdi)</span>
                                            </td>
                                            <td class="item-qty">atılan yorum sayısı<img src="@Url.Content("~/Content/Temaicerik/")images/yorum.ico" alt="Yorum"></td>
                                            <td class="item-price">@Html.DisplayFor(modelItem => item.Tarih)</td>
                                            <td class="item-price">@Html.DisplayFor(modelItem => item.Saat)</td>
                                        </tr>
                                    </tbody>

                                }
                            </table>
                        </div>
                        <div class="col-md-9 single_blog_sidebar wow fadeInUp">
                            <table>
                                <thead>
                                    <tr>
                                        <th scope="col">@Html.ActionLink(@Resources.Anasayfa.turk, "Ekranayaz", "Makales")</th>
                                        <th scope="col" align="center"><img src="@Url.Content("~/Content/Temaicerik/")images/yorum.ico" alt="Yorum"></th>
                                        <th scope="col" align="center"><img src="@Url.Content("~/Content/Temaicerik/")images/saat.ico" alt="Saat"></th>
                                        <th scope="col" align="center"><img src="@Url.Content("~/Content/Temaicerik/")images/tarih.ico" alt="Tarih"></th>
                                    </tr>
                                </thead>
                                @foreach (var item in Model)
                                {

                                    <tbody>
                                        <tr>
                                            <td>
                                                <strong class="book-title">@Html.DisplayFor(modelItem => item.Baslik)</strong>
                                                <span class="text-offset">@Html.DisplayFor(modelItem => item.Uye.KullaniciAdi)</span>
                                            </td>
                                            <td class="item-qty">atılan yorum sayısı<img src="@Url.Content("~/Content/Temaicerik/")images/yorum.ico" alt="Yorum"></td>
                                            <td class="item-price">@Html.DisplayFor(modelItem => item.Tarih)</td>
                                            <td class="item-price">@Html.DisplayFor(modelItem => item.Saat)</td>
                                        </tr>
                                    </tbody>

                                }
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

WebProgramlamaDeneme_25/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>